import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input: '../OpenAPI.yml',
    output: {
      mode: 'split',
      target: 'src/api/generated',
      client: 'axios',
      prettier: true,
      override: {
        mutator: {
          path: 'src/api/http/axios-instance.ts',
          name: 'createAxiosInstance',
        },
        header: () =>
          `// AUTO-GENERATED BY ORVAL. DO NOT EDIT.
// Run: npm run api:generate
`,
        operations: {
          // enable react-query hooks for all operations
          // @ts-ignore
          '*': {
            useQuery: true,
            useMutation: true,
            queryOptions: {
              staleTime: 60_000,
            },
          },
        },
      },
      // generate also schemas as zod if needed later
      // schemas: true,
    },
  },
});

