import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input: '../OpenAPI.yml',
    output: {
      mode: 'split',
      target: 'src/api/generated',
      client: 'react-query',
      prettier: true,
      clean: true,
      header: () => `// AUTO-GENERATED BY ORVAL. DO NOT EDIT.\n// Run: npm run api:generate\n`,
      // schemas: true,
    },
    override: {
      mutator: {
        path: 'src/api/http/axios-instance.ts',
        name: 'createAxiosInstance',
      },
      operations: {
        '*': {
          useQuery: true,
          useMutation: true,
          queryOptions: {
            staleTime: 60_000,
          },
        },
      },
    },
  },
});

